### ISSUE TITLE
EMEError: Platform does not support navigator.requestMediaKeySystemAccess

### ISSUE THREAD

**Issue by harshil-darji** [gilbarbara/react-spotify-web-playback#54]
I have created a Spotify app and trying to run it locally on my WIFi. However, when I use SpotifyPlayer, I am getting the following error:

```javascript
Uncaught (in promise) EMEError: Platform does not support navigator.requestMediaKeySystemAccess
    at new e (https://sdk.scdn.co/embedded/index.js:119:253)
    at Function.e.fatal (https://sdk.scdn.co/embedded/index.js:119:516)
    at https://sdk.scdn.co/embedded/index.js:55:2946
    at new Promise (<anonymous>)
    at Function.r.create (https://sdk.scdn.co/embedded/index.js:55:2867)
    at Function.t.create (https://sdk.scdn.co/embedded/index.js:79:6011)
    at https://sdk.scdn.co/embedded/index.js:137:2839
    at new Promise (<anonymous>)
    at createPlayer (https://sdk.scdn.co/embedded/index.js:137:2217)
    at Object.createStreamerForClient (https://sdk.scdn.co/embedded/index.js:271:2104)
```

The same app did work on localhost. I also tried disabling Chrome's Hardware Media Key Handling which might be causing the issue but no luck.

**Comment by armanbalani** [comment]
I'm having this same issue

**Comment by kc1nn4y** [comment]
Same for me

**Comment by armanbalani** [comment]
So I tried it again but this time with an SSL certificate registered on my app and it worked perfectly. It seems that chrome has these security measures in place to to block EME from unsecured websites.

**Comment by kc1nn4y** [comment]
> So I tried it again but this time with an SSL certificate registered on my app and it worked perfectly. It seems that chrome has these security measures in place to to block EME from unsecured websites.

Thank you man appreciate it! I will try this out

**Comment by cuneytyvz** [comment]
@armanbalani Hi, do you mean your app runs on https now and before it was http?

**Comment by armanbalani** [comment]
> @armanbalani Hi, do you mean your app runs on https now and before it was http?

Yes exactly
